name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

env:
  DESTDIR: ./bin
  DOCKER_BUILD_SUMMARY: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint
        uses: docker/bake-action@v6
        with:
          targets: lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
          - "1.22"
          - "1.23"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Test
        uses: docker/bake-action@v6
        with:
          targets: test
        env:
          GO_VERSION: ${{ matrix.go }}
      -
        name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          directory: ${{ env.DESTDIR }}/coverage
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            repo: "moby/moby"
            ref: "v27.4.1"
            wd: "./integration-cli"
          -
            repo: "crazy-max/diun"
            ref: "v4.29.0"
            wd: "."
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      -
        name: Install gotestlist
        run: |
          go install ./cmd/gotestlist
      -
        name: Checkout ${{ matrix.repo }} for testing
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: project
      -
        name: Run gotestlist
        working-directory: project/${{ matrix.wd }}
        run: |
          gotestlist -d 6 ./... | jq '.'
