name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

env:
  DESTDIR: ./bin
  DOCKER_BUILD_SUMMARY: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      -
        name: Lint
        uses: docker/bake-action@4a9a8d494466d37134e2bfca2d3a8de8fb2681ad # v5.13.0
        with:
          targets: lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
          - "1.22"
          - "1.23"
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      -
        name: Test
        uses: docker/bake-action@4a9a8d494466d37134e2bfca2d3a8de8fb2681ad # v5.13.0
        with:
          targets: test
        env:
          GO_VERSION: ${{ matrix.go }}
      -
        name: Upload coverage
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          directory: ${{ env.DESTDIR }}/coverage
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            repo: "moby/moby"
            ref: "v27.4.1"
            wd: "./integration-cli"
          -
            repo: "crazy-max/diun"
            ref: "v4.29.0"
            wd: "."
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      -
        name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "1.23"
      -
        name: Install gotestlist
        run: |
          go install ./cmd/gotestlist
      -
        name: Checkout ${{ matrix.repo }} for testing
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: project
      -
        name: Run gotestlist
        working-directory: project/${{ matrix.wd }}
        run: |
          gotestlist -d 6 ./... | jq '.'
